[tool.poetry]
name = "intake-cryoem"
version = "0.0.1"
description = ""
authors = ["mooniean <bcostagomes@turing.ac.uk>", "ots22 <ostrickson@turing.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
intake = "^0.6.5"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git@main"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."intake.drivers"]
mrc = "intake_cryoem.mrcsource:MrcSource"
star = "intake_cryoem.starsource:StarSource"
empiar = "intake_cryoem.empiar:EmpiarCatalog"
